# Generated by Django 3.0.1 on 2020-06-11 15:44

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('address', models.CharField(max_length=50)),
                ('bus_station_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField(default=datetime.datetime(2020, 6, 11, 15, 44, 39, 509973, tzinfo=utc))),
                ('bus_station_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buses.BusStation')),
            ],
        ),
    ]
