# Generated by Django 3.0.1 on 2020-06-17 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timings',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 6, 17, 7, 22, 25, 578146, tzinfo=utc)),
        ),
    ]
