# Generated by Django 3.0.1 on 2020-06-17 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_auto_20200617_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstation',
            name='lati',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='busstation',
            name='longi',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='timings',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 6, 17, 13, 51, 44, 273728, tzinfo=utc)),
        ),
    ]
