# Generated by Django 3.0.1 on 2020-06-17 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_auto_20200617_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timings',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 6, 17, 13, 52, 10, 106590, tzinfo=utc)),
        ),
    ]
