# Generated by Django 3.0.1 on 2020-06-17 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0006_auto_20200617_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstation',
            old_name='latitud',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='busstation',
            old_name='longitud',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='timings',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 6, 17, 14, 30, 3, 877509, tzinfo=utc)),
        ),
    ]
